stages:
  - install
  - verify

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules

image: node:12-alpine

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - npm install -g nx
    - npm ci

build:
  stage: verify
  script:
    - nx affected:build --all

