stages:
  - install
  - verify

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules

image: node:12

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - npm install

build:
  stage: verify
  before_script:
    - git fetch origin
  script:
    - npm run affected:build
